import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars, faXmark } from '@fortawesome/free-solid-svg-icons'
import Head from "next/head";
import Link from "next/link";
import React, { FC, useState } from "react";

type Props = {
  children: React.ReactNode,
  categories: any,
};

type Menu = {
  name: string;
  url: string;
}


const Layout: FC<Props> = ({ children, categories }) => {
  const [openHamburgerMenu, setOpenHamburgerMenu] = useState(false);
  
  const menuList: Menu[] = [
    { 
      name: 'ホーム',
      url: '/',
    },
    {
      name: 'プログラミング',
      url: '/categories/r9ixaserz',
    },
    {
      name: 'デザイン',
      url: '/categories/7x-thb4d2',
    },
    {
      name: 'ブログ',
      url: '/',
    },
  ];

  const nowYear = new Date().getFullYear();

  const menuFunction = () => {
    setOpenHamburgerMenu(!openHamburgerMenu);
  };
  

  return (
    <div className="font-body bg-[#EAEAEA]">
      <Head>
        <title>くまさんのカフェ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* ナビゲーション */}
      <header className="m-auto bg-original-blue text-white">
        <div className="container mx-auto flex flex-wrap py-2 pl-2 pr-6 flex-row items-center max-w-7xl">
          <h1>
            <Link href="/">
              <a>
                <img src="/images/blog-logo.png" 
                    alt="くまさんのカフェ" 
                    title="くまさんのカフェ"
                    className="md:h-12 h-9"/>
              </a>
            </Link>
          </h1>
          <nav className="ml-4 lg:inline-block hidden">
            <ul className="flex flex-row items-center text-sm justify-center font-semibold">
              {menuList.map((menu: Menu, i: number) => {
                return (
                  <li key={i} className="mr-4">
                    <Link href={menu.url}>
                      <a className="">{menu.name}</a>
                    </Link>
                  </li>
                );
              })}
            </ul>
          </nav>

          {/* ハンバーガーボタン */}
          <button onClick={menuFunction} type="button" className="z-40 ml-auto flex w-6 items-center justify-end">
            <span className="sr-only">Open navigation</span>
            <FontAwesomeIcon icon={faBars} />
          </button>
        
          {/* ハンバーガーメニュー */}
          <nav className={"bg-original-blue mx-auto h-screen px-6 md:w-96 w-full fixed z-50 transition-all duration-300 top-0 " + (openHamburgerMenu ? "right-0" : "-right-[100%]")}>
            <div className="flex justify-center items-center md:h-16 h-9">
              <button onClick={menuFunction} type="button" className="ml-auto flex w-6">
                <span className="sr-only">Open navigation</span>
                <FontAwesomeIcon icon={faXmark} />
              </button>
            </div>
            <ul className="items-center text-lg text-white justify-center">
              {menuList.map((menu: Menu, i: number) => {
                return (
                  <li key={i} className="py-4 border-b">
                    <Link href="/"><a className="w-full block" onClick={menuFunction}>{menu.name}</a></Link>
                  </li>
                );
              })}
            </ul>
          </nav>
          
        </div>
      </header>

      <div className="container md:flex block mx-auto py-8 md:mt-10 mt-4 max-w-7xl text-gray-900">
        <div className="md:w-3/4 w-full">
          <main>{children}</main>
        </div>
        
        <div className="md:w-1/4 w-full md:mt-0 mt-16 md:p-0 px-4">
          <aside className="border p-4 mb-8 bg-white">
            <img src="/images/IMG_0618.png" 
                      alt="クマオ" 
                      title="クマオ"
                      className="h-32 mx-auto"/>
            <div className="text-center">クマオ</div>
            <div className="py-4 text-sm">
              地方のIT企業で7年間Sierしていました。今はWeb系開発エンジニアやってます。<br/>
              <br/>
              ものづくりが大好きな繊細さん。<br/>
              日々多くのストレスと戦いながら、今日も生活のため働きます。<br/>
              <br/>
              主にコーディングやプログラミングを勉強中の方向けの記事を投稿します。<br/>
              <br/>
              【使用言語】<br/>
              PHP、Python、HTML、CSS、JavaScript、jQuery、VB.Net、Java<br/>
              <br/>
              【取得資格】<br/>
              <ul className="list-disc pl-4">
                <li>応用情報技術者</li>
                <li>漢検2級</li>
              </ul>
            </div>
          </aside>
          <aside className="border bg-white">
            <div className="p-[2px] bg-original-blue text-white">
              <div className="border-[0.5px] py-1 pl-2 border-white">
                カテゴリー
              </div>
            </div>
            <ul className="m-4 border">
              {categories.map((category: any, i: number) => {
                return (
                  <li key={i} className="border-b hover:bg-original-blue hover:text-white transition-all duration-200">
                    <Link href={`/categories/${category.id}`}>
                      <a className="flex p-2">
                        {category.name}
                        <div className="ml-auto text-sm border border-gray-300 rounded-md px-1">{category.count}</div>
                      </a>
                    </Link>
                  </li>
                );
              })}
            </ul>
          </aside>
        </div>
      </div>

      <footer className="text-white text-sm">
        <div className="bg-original-blue px-5 py-4 mx-auto flex items-center">
          
        </div>
        <div className="bg-black px-5 py-4 mx-auto">
          <div className="flex justify-center mt-4 text-xs">© Copyright {nowYear} 
            <Link href={"/"}>
              <a className="font-bold">クマさんのカフェ.</a>
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default Layout;